import { Router, Request, Response } from 'express';

const router = Router();

/**
 * GET /repos - List user's GitHub repos
 * Requires x-github-token header
 */
router.get('/repos', async (req: Request, res: Response) => {
  const token = req.headers['x-github-token'] as string;

  if (!token) {
    return res.status(401).json({
      success: false,
      error: 'GitHub token required. Connect your GitHub account or provide a token.',
    });
  }

  try {
    const response = await fetch(
      'https://api.github.com/user/repos?sort=updated&per_page=100&type=owner',
      {
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github.v3+json',
          'User-Agent': 'Genie-AI',
        },
      }
    );

    if (!response.ok) {
      const errorBody = await response.text();
      console.error('GitHub API error:', response.status, errorBody);
      return res.status(response.status).json({
        success: false,
        error: `GitHub API error: ${response.statusText}`,
      });
    }

    const repos = await response.json();

    const mapped = repos.map((repo: any) => ({
      id: repo.id,
      name: repo.name,
      fullName: repo.full_name,
      description: repo.description,
      private: repo.private,
      url: repo.html_url,
      updatedAt: repo.updated_at,
      language: repo.language,
      defaultBranch: repo.default_branch,
    }));

    return res.json({ success: true, data: mapped });
  } catch (error: any) {
    console.error('GitHub repos error:', error);
    return res.status(500).json({
      success: false,
      error: error.message || 'Failed to fetch repositories',
    });
  }
});

/**
 * POST /push - Push files to a GitHub repo (new or existing)
 * Requires x-github-token header
 * Body: { repoName, files, commitMessage, createNew?, description?, isPrivate? }
 */
router.post('/push', async (req: Request, res: Response) => {
  const token = req.headers['x-github-token'] as string;

  if (!token) {
    return res.status(401).json({
      success: false,
      error: 'GitHub token required.',
    });
  }

  const { repoName, files, commitMessage, createNew, description, isPrivate } =
    req.body;

  if (!repoName || !files || !Array.isArray(files) || files.length === 0) {
    return res.status(400).json({
      success: false,
      error: 'repoName and files are required.',
    });
  }

  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github.v3+json',
    'Content-Type': 'application/json',
    'User-Agent': 'Genie-AI',
  };

  try {
    // Get authenticated user
    const userRes = await fetch('https://api.github.com/user', { headers });
    if (!userRes.ok) {
      return res.status(401).json({
        success: false,
        error: 'Invalid GitHub token.',
      });
    }
    const user = await userRes.json();
    const owner = user.login;

    let repoFullName = `${owner}/${repoName}`;
    let defaultBranch = 'main';

    // Create repo if requested
    if (createNew) {
      const createRes = await fetch('https://api.github.com/user/repos', {
        method: 'POST',
        headers,
        body: JSON.stringify({
          name: repoName,
          description: description || `Generated by Genie AI`,
          private: isPrivate ?? false,
          auto_init: true,
        }),
      });

      if (!createRes.ok) {
        const err = await createRes.json();
        return res.status(createRes.status).json({
          success: false,
          error: err.message || 'Failed to create repository',
        });
      }

      const newRepo = await createRes.json();
      repoFullName = newRepo.full_name;
      defaultBranch = newRepo.default_branch || 'main';

      // Wait briefly for auto_init to complete
      await new Promise((r) => setTimeout(r, 2000));
    } else {
      // Get existing repo info
      const repoRes = await fetch(
        `https://api.github.com/repos/${repoFullName}`,
        { headers }
      );
      if (!repoRes.ok) {
        return res.status(404).json({
          success: false,
          error: `Repository ${repoFullName} not found.`,
        });
      }
      const repo = await repoRes.json();
      defaultBranch = repo.default_branch || 'main';
    }

    // Get latest commit SHA on default branch
    const refRes = await fetch(
      `https://api.github.com/repos/${repoFullName}/git/ref/heads/${defaultBranch}`,
      { headers }
    );
    if (!refRes.ok) {
      return res.status(500).json({
        success: false,
        error: 'Failed to get branch reference. Repository may be empty.',
      });
    }
    const refData = await refRes.json();
    const latestCommitSha = refData.object.sha;

    // Get the tree SHA of the latest commit
    const commitRes = await fetch(
      `https://api.github.com/repos/${repoFullName}/git/commits/${latestCommitSha}`,
      { headers }
    );
    const commitData = await commitRes.json();
    const baseTreeSha = commitData.tree.sha;

    // Create blobs for each file
    const treeItems = await Promise.all(
      files.map(async (file: { path: string; content: string }) => {
        const blobRes = await fetch(
          `https://api.github.com/repos/${repoFullName}/git/blobs`,
          {
            method: 'POST',
            headers,
            body: JSON.stringify({
              content: file.content,
              encoding: 'utf-8',
            }),
          }
        );
        const blob = await blobRes.json();
        return {
          path: file.path,
          mode: '100644' as const,
          type: 'blob' as const,
          sha: blob.sha,
        };
      })
    );

    // Create a new tree
    const treeRes = await fetch(
      `https://api.github.com/repos/${repoFullName}/git/trees`,
      {
        method: 'POST',
        headers,
        body: JSON.stringify({
          base_tree: baseTreeSha,
          tree: treeItems,
        }),
      }
    );
    const treeData = await treeRes.json();

    // Create a new commit
    const newCommitRes = await fetch(
      `https://api.github.com/repos/${repoFullName}/git/commits`,
      {
        method: 'POST',
        headers,
        body: JSON.stringify({
          message: commitMessage || 'Add files from Genie AI',
          tree: treeData.sha,
          parents: [latestCommitSha],
        }),
      }
    );
    const newCommit = await newCommitRes.json();

    // Update the reference to point to the new commit
    const updateRefRes = await fetch(
      `https://api.github.com/repos/${repoFullName}/git/refs/heads/${defaultBranch}`,
      {
        method: 'PATCH',
        headers,
        body: JSON.stringify({
          sha: newCommit.sha,
        }),
      }
    );

    if (!updateRefRes.ok) {
      return res.status(500).json({
        success: false,
        error: 'Failed to update branch reference.',
      });
    }

    return res.json({
      success: true,
      data: {
        repoUrl: `https://github.com/${repoFullName}`,
        commitSha: newCommit.sha,
      },
    });
  } catch (error: any) {
    console.error('GitHub push error:', error);
    return res.status(500).json({
      success: false,
      error: error.message || 'Failed to push to GitHub',
    });
  }
});

export default router;
